/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.BuyerRole;

import Business.EcoSystem;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import ui.SystemAdminRole.SystemAdminWorkAreaJPanel;


public class ViewVehicleInfoJPanel extends javax.swing.JPanel {
    public JPanel container;
    public EcoSystem business;
    WorkRequest car;

    /**
     * Creates new form ViewVehicleInfoJPanel
     */
    public ViewVehicleInfoJPanel(JPanel userProcessContainer, EcoSystem business, WorkRequest car) {
        initComponents();
        this.container = userProcessContainer;
        this.business = business;
        this.car = car;
        View();
    }
    
    public void View(){
        txtMake.setText(car.getMake());       
        txtModel.setText(car.getModel());
        txtYear.setText(car.getYear());
        txtCategory.setText(car.getCategory());
        txtState.setText(car.getState());
        txtCity.setText(car.getCity());
        txtVin.setText(car.getVin());
        txtMileage.setText(car.getMileage());
        txtHorsepower.setText(car.getHorsepower());
        txtInterColor.setText(car.getInColor());
        txtTransmission.setText(car.getTransmission());
        txtFuelType.setText(car.getFuelType());
        txtMpgCity.setText(car.getMpgCity());
        txtMpgHwy.setText(car.getMpgHwy());
        txtDrivetrain.setText(car.getDrivetrain());
        ImageIcon icon = new ImageIcon(car.getFrontPicture());
        img.setIcon(icon);  
        ImageIcon icon1 = new ImageIcon(car.getBackPicture());
        img1.setIcon(icon1); 
        ImageIcon icon2 = new ImageIcon(car.getDashBoardPicture());
        img2.setIcon(icon2); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtInterColor = new javax.swing.JTextField();
        txtFuelType = new javax.swing.JTextField();
        img = new javax.swing.JLabel();
        txtTransmission = new javax.swing.JTextField();
        txtMpgCity = new javax.swing.JTextField();
        img1 = new javax.swing.JLabel();
        txtDrivetrain = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        txtCategory = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMake = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        txtVin = new javax.swing.JTextField();
        txtMpgHwy = new javax.swing.JTextField();
        txtMileage = new javax.swing.JTextField();
        txtHorsepower = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setLayout(null);

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 153, 255));
        jLabel22.setText("/City");
        add(jLabel22);
        jLabel22.setBounds(204, 539, 40, 19);

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 153, 255));
        jLabel23.setText("hp");
        add(jLabel23);
        jLabel23.setBounds(244, 363, 30, 19);
        add(txtInterColor);
        txtInterColor.setBounds(138, 402, 100, 24);
        add(txtFuelType);
        txtFuelType.setBounds(138, 446, 100, 24);
        add(img);
        img.setBounds(550, 10, 184, 128);
        add(txtTransmission);
        txtTransmission.setBounds(138, 490, 100, 24);
        add(txtMpgCity);
        txtMpgCity.setBounds(138, 534, 60, 24);
        add(img1);
        img1.setBounds(550, 180, 184, 128);
        add(txtDrivetrain);
        txtDrivetrain.setBounds(138, 578, 100, 24);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 153, 255));
        jLabel9.setText("/Hwy");
        add(jLabel9);
        jLabel9.setBounds(310, 539, 50, 19);
        add(img2);
        img2.setBounds(540, 390, 184, 128);
        add(txtYear);
        txtYear.setBounds(138, 94, 100, 24);
        add(txtCategory);
        txtCategory.setBounds(138, 138, 100, 24);
        add(txtState);
        txtState.setBounds(138, 182, 100, 24);

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 153, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Make:");
        add(jLabel16);
        jLabel16.setBounds(6, 11, 40, 19);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("VIN:");
        add(jLabel1);
        jLabel1.setBounds(6, 275, 26, 19);
        add(txtCity);
        txtCity.setBounds(138, 226, 100, 24);

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 153, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Model:");
        add(jLabel17);
        jLabel17.setBounds(6, 55, 50, 19);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Mileage:");
        add(jLabel2);
        jLabel2.setBounds(6, 319, 60, 19);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 153, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Horsepower:");
        add(jLabel3);
        jLabel3.setBounds(6, 363, 80, 19);

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 153, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Year:");
        add(jLabel18);
        jLabel18.setBounds(0, 100, 40, 19);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 153, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Interior color:");
        add(jLabel4);
        jLabel4.setBounds(0, 400, 100, 19);

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 153, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Category:");
        add(jLabel19);
        jLabel19.setBounds(6, 143, 70, 19);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 153, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Fuel type:");
        add(jLabel5);
        jLabel5.setBounds(6, 451, 70, 19);

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 153, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("State:");
        add(jLabel20);
        jLabel20.setBounds(6, 187, 40, 19);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 153, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Transmission:");
        add(jLabel6);
        jLabel6.setBounds(6, 495, 100, 19);

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 153, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("City:");
        add(jLabel21);
        jLabel21.setBounds(6, 231, 28, 19);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 153, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("MPG:");
        add(jLabel7);
        jLabel7.setBounds(6, 539, 50, 19);
        add(txtMake);
        txtMake.setBounds(138, 6, 100, 24);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 153, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Drivetrain::");
        add(jLabel8);
        jLabel8.setBounds(6, 583, 70, 19);
        add(txtModel);
        txtModel.setBounds(138, 50, 100, 24);
        add(txtVin);
        txtVin.setBounds(138, 270, 100, 24);
        add(txtMpgHwy);
        txtMpgHwy.setBounds(244, 534, 60, 24);
        add(txtMileage);
        txtMileage.setBounds(138, 314, 100, 24);
        add(txtHorsepower);
        txtHorsepower.setBounds(138, 358, 100, 24);

        backJButton.setBackground(new java.awt.Color(255, 204, 204));
        backJButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        backJButton.setForeground(new java.awt.Color(102, 153, 255));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(58, 658, 83, 27);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/3439d73c70642d1039f6fdc9345403a3.jpeg"))); // NOI18N
        jLabel10.setText("jLabel10");
        add(jLabel10);
        jLabel10.setBounds(0, -30, 1440, 970);
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel img;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDrivetrain;
    private javax.swing.JTextField txtFuelType;
    private javax.swing.JTextField txtHorsepower;
    private javax.swing.JTextField txtInterColor;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtMileage;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtMpgCity;
    private javax.swing.JTextField txtMpgHwy;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtTransmission;
    private javax.swing.JTextField txtVin;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
