/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.BuyerRole;

import Business.EcoSystem;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import ui.SystemAdminRole.SystemAdminWorkAreaJPanel;


public class ViewVehicleConditionReportJPanel extends javax.swing.JPanel {
    public JPanel container;
    public EcoSystem business;
    WorkRequest car;

    /**
     * Creates new form ViewVehicleConditionReportJPanel
     */
    public ViewVehicleConditionReportJPanel(JPanel userProcessContainer, EcoSystem business, WorkRequest car) {
        initComponents();
        this.container = userProcessContainer;
        this.business = business;
        this.car = car;
        View();
    }
    
    public void View(){
        jTextField1.setText(car.getQ1());
        jTextField2.setText(car.getQ2());
        jTextField3.setText(car.getQ3());
        jTextField4.setText(car.getQ4());
        jTextField5.setText(car.getQ5());
        jTextField6.setText(car.getQ6());
        jTextField7.setText(car.getQ7());
        jTextField8.setText(car.getQ8());
        jTextField9.setText(car.getQ9());
        jTextField10.setText(car.getQ10());
        jTextField11.setText(car.getQ11());
        jTextField12.setText(car.getQ12());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setLayout(null);
        add(jTextField2);
        jTextField2.setBounds(770, 230, 247, 24);
        add(jTextField1);
        jTextField1.setBounds(770, 200, 247, 24);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 153, 255));
        jLabel12.setText("12.Are there any other issues with the vehicle?");
        add(jLabel12);
        jLabel12.setBounds(210, 560, 552, 19);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 153, 255));
        jLabel11.setText("11.Does the vehicle have any aftermarket modifications?");
        add(jLabel11);
        jLabel11.setBounds(210, 530, 552, 19);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 153, 255));
        jLabel10.setText("10.How many keys does the car have?");
        add(jLabel10);
        jLabel10.setBounds(210, 500, 552, 19);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 153, 255));
        jLabel9.setText("9.Do any tires need to be replaced?");
        add(jLabel9);
        jLabel9.setBounds(210, 470, 552, 19);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 153, 255));
        jLabel8.setText("8.Are there any rips, tears, or stains in the interior?");
        add(jLabel8);
        jLabel8.setBounds(210, 430, 552, 19);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 153, 255));
        jLabel7.setText("7.Are any interior parts broken or inoperable?");
        add(jLabel7);
        jLabel7.setBounds(210, 400, 552, 19);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 153, 255));
        jLabel6.setText("6.Are there any panels in need of paint or body work?");
        add(jLabel6);
        jLabel6.setBounds(210, 370, 552, 19);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 153, 255));
        jLabel5.setText("5.Has this odometer ever been broken or replaced?");
        add(jLabel5);
        jLabel5.setBounds(210, 340, 552, 19);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 153, 255));
        jLabel4.setText("4.Are there any mechanical issues or warning lights displayed on the dashboard?");
        add(jLabel4);
        jLabel4.setBounds(210, 310, 516, 19);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 153, 255));
        jLabel3.setText("3.Does the vehicle have any frame damage?");
        add(jLabel3);
        jLabel3.setBounds(210, 270, 552, 19);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 153, 255));
        jLabel2.setText("2.Does the vehicle have any flood damage?");
        add(jLabel2);
        jLabel2.setBounds(210, 230, 552, 19);
        add(jTextField12);
        jTextField12.setBounds(770, 560, 247, 24);
        add(jTextField11);
        jTextField11.setBounds(770, 520, 247, 24);
        add(jTextField10);
        jTextField10.setBounds(770, 490, 247, 24);
        add(jTextField9);
        jTextField9.setBounds(770, 460, 247, 24);
        add(jTextField8);
        jTextField8.setBounds(770, 430, 247, 24);
        add(jTextField7);
        jTextField7.setBounds(770, 400, 247, 24);
        add(jTextField6);
        jTextField6.setBounds(770, 360, 247, 24);
        add(jTextField5);
        jTextField5.setBounds(770, 330, 247, 24);
        add(jTextField4);
        jTextField4.setBounds(770, 300, 247, 24);
        add(jTextField3);
        jTextField3.setBounds(770, 260, 247, 24);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setText("1.Has the vehicle ever been in an accident?");
        add(jLabel1);
        jLabel1.setBounds(210, 200, 552, 19);

        backJButton.setBackground(new java.awt.Color(255, 204, 204));
        backJButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        backJButton.setForeground(new java.awt.Color(102, 153, 255));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(30, 50, 83, 27);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/3439d73c70642d1039f6fdc9345403a3.jpeg"))); // NOI18N
        jLabel13.setText("jLabel13");
        add(jLabel13);
        jLabel13.setBounds(-7, -4, 1250, 790);
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
