/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.UserAdminRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Organization.OrganizationDirectory;
import Business.Router;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ui.SystemAdminRole.SystemAdminWorkArea;

/**
 *
 * @author Ke
 */
public class ManageOrganization extends javax.swing.JPanel {

    //private OrganizationDirectory directory;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    EcoSystem system;
    
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrganization(JPanel userProcessContainer,EcoSystem system,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.enterprise = enterprise;
        
        populateCombo();
    }
    
    private void populateCombo(){
        organizationJComboBox.removeAllItems();
        if(enterprise.getEnterpriseType().getValue().equals(EnterpriseType.Rent.getValue()))
        {
           for (Type type : Organization.Type.values()){
                if (type.getValue().equals(Type.Buyer.getValue()))
                    organizationJComboBox.addItem(type);
                if (type.getValue().equals(Type.CustomerService.getValue()))
                    organizationJComboBox.addItem(type);
                if (type.getValue().equals(Type.Receptionist.getValue()))
                    organizationJComboBox.addItem(type);
            } 
        }
        if(enterprise.getEnterpriseType().getValue().equals(EnterpriseType.Publish.getValue()))
        {
           for (Type type : Organization.Type.values()){
                if (type.getValue().equals(Type.Seller.getValue()))
                    organizationJComboBox.addItem(type);
                if (type.getValue().equals(Type.CustomerService.getValue()))
                    organizationJComboBox.addItem(type);
            } 
        }
        if(enterprise.getEnterpriseType().getValue().equals(EnterpriseType.RentService.getValue()))
        {
           for (Type type : Organization.Type.values()){
                if (type.getValue().equals(Type.VehicleConditionInspector.getValue()))
                    organizationJComboBox.addItem(type);
                if (type.getValue().equals(Type.Accounter.getValue()))
                    organizationJComboBox.addItem(type);
                if (type.getValue().equals(Type.Warranter.getValue()))
                    organizationJComboBox.addItem(type);
            } 
        }
        if(enterprise.getEnterpriseType().getValue().equals(EnterpriseType.CustomerService.getValue()))
        {
           for (Type type : Organization.Type.values()){
                if (type.getValue().equals(Type.CustomerService.getValue()))
                    organizationJComboBox.addItem(type);
            } 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addJButton = new javax.swing.JButton();
        organizationJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        addJButton.setBackground(new java.awt.Color(51, 153, 255));
        addJButton.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        addJButton.setForeground(new java.awt.Color(255, 255, 255));
        addJButton.setText("Add Organization");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton);
        addJButton.setBounds(380, 490, 160, 31);

        organizationJComboBox.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        organizationJComboBox.setForeground(new java.awt.Color(51, 153, 255));
        organizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJComboBoxActionPerformed(evt);
            }
        });
        add(organizationJComboBox);
        organizationJComboBox.setBounds(510, 310, 160, 28);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Organization Type ");
        add(jLabel1);
        jLabel1.setBounds(290, 310, 138, 22);

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 153, 255));
        jLabel10.setText("Manage organization");
        add(jLabel10);
        jLabel10.setBounds(40, 40, 240, 34);

        jLabel8.setText("—————————————————————————————————————————————————");
        add(jLabel8);
        jLabel8.setBounds(110, 80, 735, 18);
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed

        Type type = (Type) organizationJComboBox.getSelectedItem();
        enterprise.getOrganizationDirectory().createOrganization(type);
        DB4OUtil.getInstance().storeSystem(system);
        JOptionPane.showMessageDialog(this,"Organization Created");
    }//GEN-LAST:event_addJButtonActionPerformed

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organizationJComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox organizationJComboBox;
    // End of variables declaration//GEN-END:variables
}
