/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.UserAdminRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ke
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    //private OrganizationDirectory directory;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrganizationJPanel(JPanel userProcessContainer,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        
        populateCombo();
    }
    
    private void populateCombo(){
        organizationJComboBox.removeAllItems();
        if(enterprise.getEnterpriseType().getValue().equals(EnterpriseType.Rent.getValue()))
        {
           for (Type type : Organization.Type.values()){
                if (type.getValue().equals(Type.Buyer.getValue()))
                    organizationJComboBox.addItem(type);
                if (type.getValue().equals(Type.CustomerService.getValue()))
                    organizationJComboBox.addItem(type);
                if (type.getValue().equals(Type.Receptionist.getValue()))
                    organizationJComboBox.addItem(type);
            } 
        }
        if(enterprise.getEnterpriseType().getValue().equals(EnterpriseType.Publish.getValue()))
        {
           for (Type type : Organization.Type.values()){
                if (type.getValue().equals(Type.Seller.getValue()))
                    organizationJComboBox.addItem(type);
                if (type.getValue().equals(Type.CustomerService.getValue()))
                    organizationJComboBox.addItem(type);
            } 
        }
        if(enterprise.getEnterpriseType().getValue().equals(EnterpriseType.RentService.getValue()))
        {
           for (Type type : Organization.Type.values()){
                if (type.getValue().equals(Type.VehicleConditionInspector.getValue()))
                    organizationJComboBox.addItem(type);
                if (type.getValue().equals(Type.Appraiser.getValue()))
                    organizationJComboBox.addItem(type);
                if (type.getValue().equals(Type.Warranter.getValue()))
                    organizationJComboBox.addItem(type);
            } 
        }
        if(enterprise.getEnterpriseType().getValue().equals(EnterpriseType.CustomerService.getValue()))
        {
           for (Type type : Organization.Type.values()){
                if (type.getValue().equals(Type.CustomerService.getValue()))
                    organizationJComboBox.addItem(type);
            } 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addJButton = new javax.swing.JButton();
        organizationJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        addJButton.setBackground(new java.awt.Color(255, 204, 204));
        addJButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        addJButton.setForeground(new java.awt.Color(102, 153, 255));
        addJButton.setText("Add Organization");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton);
        addJButton.setBounds(420, 350, 143, 27);

        organizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJComboBoxActionPerformed(evt);
            }
        });
        add(organizationJComboBox);
        organizationJComboBox.setBounds(550, 230, 160, 24);

        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setText("Organization Type ");
        add(jLabel1);
        jLabel1.setBounds(330, 230, 144, 18);

        backJButton.setBackground(new java.awt.Color(255, 204, 204));
        backJButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        backJButton.setForeground(new java.awt.Color(102, 153, 255));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(30, 30, 83, 27);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/6905b594d7eab2eafa12cd1d1022f3cd.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(-5, -4, 1330, 770);
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed

        Type type = (Type) organizationJComboBox.getSelectedItem();
        enterprise.getOrganizationDirectory().createOrganization(type);
        JOptionPane.showMessageDialog(this,"Organization Created");
    }//GEN-LAST:event_addJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organizationJComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox organizationJComboBox;
    // End of variables declaration//GEN-END:variables
}
