/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SellerRole;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import static com.db4o.foundation.io.File4.copyFile;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.nio.channels.FileChannel;
import javax.swing.filechooser.FileNameExtensionFilter;
import ui.SystemAdminRole.SystemAdminWorkAreaJPanel;

/**
 *
 * @author Zhe Li
 */
public class VehicleInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SellerVehicleSummaryJPanel
     */
    //Zhe Li
    public JPanel container;
    public EcoSystem business;
    private UserAccount userAccount;
    String path1 ="";
    String path2 ="";
    String path3 ="";
    
    public VehicleInfoJPanel(JPanel userProcessContainer, EcoSystem business, UserAccount userAccount) {
        initComponents();
        this.container = userProcessContainer;
        this.business = business;
        this.userAccount = userAccount;
    }
    
    
    public VehicleInfoJPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtVin = new javax.swing.JTextField();
        txtMileage = new javax.swing.JTextField();
        txtHorsepower = new javax.swing.JTextField();
        txtInterColor = new javax.swing.JTextField();
        txtFuelType = new javax.swing.JTextField();
        txtTransmission = new javax.swing.JTextField();
        txtMpgCity = new javax.swing.JTextField();
        txtDrivetrain = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        txtCategory = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtMake = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtMpgHwy = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnFront = new javax.swing.JButton();
        img = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        img1 = new javax.swing.JLabel();
        btnDashBoard = new javax.swing.JButton();
        img2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Make:");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Model:");

        jButton1.setText("Save");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Year:");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Category:");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("State:");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("City:");

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("VIN:");
        add(jLabel1);
        jLabel1.setBounds(10, 275, 89, 19);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Mileage:");
        add(jLabel2);
        jLabel2.setBounds(10, 319, 89, 19);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 153, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Horsepower:");
        add(jLabel3);
        jLabel3.setBounds(10, 363, 89, 19);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 153, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Interior color:");
        add(jLabel4);
        jLabel4.setBounds(10, 407, 100, 19);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 153, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Fuel type:");
        add(jLabel5);
        jLabel5.setBounds(10, 451, 89, 19);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 153, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Transmission:");
        add(jLabel6);
        jLabel6.setBounds(10, 495, 110, 19);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 153, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("MPG:");
        add(jLabel7);
        jLabel7.setBounds(10, 539, 89, 19);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 153, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Drivetrain::");
        add(jLabel8);
        jLabel8.setBounds(10, 583, 100, 19);

        txtVin.setBackground(new java.awt.Color(255, 204, 204));
        add(txtVin);
        txtVin.setBounds(171, 270, 100, 24);

        txtMileage.setBackground(new java.awt.Color(255, 204, 204));
        add(txtMileage);
        txtMileage.setBounds(171, 314, 100, 24);

        txtHorsepower.setBackground(new java.awt.Color(255, 204, 204));
        add(txtHorsepower);
        txtHorsepower.setBounds(171, 358, 100, 24);

        txtInterColor.setBackground(new java.awt.Color(255, 204, 204));
        add(txtInterColor);
        txtInterColor.setBounds(171, 402, 100, 24);

        txtFuelType.setBackground(new java.awt.Color(255, 204, 204));
        add(txtFuelType);
        txtFuelType.setBounds(171, 446, 100, 24);

        txtTransmission.setBackground(new java.awt.Color(255, 204, 204));
        add(txtTransmission);
        txtTransmission.setBounds(171, 490, 100, 24);

        txtMpgCity.setBackground(new java.awt.Color(255, 204, 204));
        add(txtMpgCity);
        txtMpgCity.setBounds(171, 534, 60, 24);

        txtDrivetrain.setBackground(new java.awt.Color(255, 204, 204));
        add(txtDrivetrain);
        txtDrivetrain.setBounds(171, 578, 100, 24);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 153, 255));
        jLabel9.setText("/Hwy");
        add(jLabel9);
        jLabel9.setBounds(350, 540, 40, 19);

        txtYear.setBackground(new java.awt.Color(255, 204, 204));
        add(txtYear);
        txtYear.setBounds(171, 94, 100, 24);

        txtCategory.setBackground(new java.awt.Color(255, 204, 204));
        add(txtCategory);
        txtCategory.setBounds(171, 138, 100, 24);

        txtState.setBackground(new java.awt.Color(255, 204, 204));
        add(txtState);
        txtState.setBounds(171, 182, 100, 24);

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 153, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Make:");
        add(jLabel16);
        jLabel16.setBounds(10, 11, 89, 19);

        txtCity.setBackground(new java.awt.Color(255, 204, 204));
        add(txtCity);
        txtCity.setBounds(171, 226, 100, 24);

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 153, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Model:");
        add(jLabel17);
        jLabel17.setBounds(10, 55, 89, 19);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(320, 690, 330, 27);

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 153, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Year:");
        add(jLabel18);
        jLabel18.setBounds(10, 99, 89, 19);

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 153, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Category:");
        add(jLabel19);
        jLabel19.setBounds(10, 143, 89, 19);

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 153, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("State:");
        add(jLabel20);
        jLabel20.setBounds(10, 187, 89, 19);

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 153, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("City:");
        add(jLabel21);
        jLabel21.setBounds(10, 231, 89, 19);

        txtMake.setBackground(new java.awt.Color(255, 204, 204));
        add(txtMake);
        txtMake.setBounds(171, 6, 100, 24);

        txtModel.setBackground(new java.awt.Color(255, 204, 204));
        add(txtModel);
        txtModel.setBounds(171, 50, 100, 24);

        txtMpgHwy.setBackground(new java.awt.Color(255, 204, 204));
        add(txtMpgHwy);
        txtMpgHwy.setBounds(280, 530, 60, 24);

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 153, 255));
        jLabel22.setText("/City");
        add(jLabel22);
        jLabel22.setBounds(237, 539, 40, 19);

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 153, 255));
        jLabel23.setText("hp");
        add(jLabel23);
        jLabel23.setBounds(277, 363, 20, 19);

        btnFront.setBackground(new java.awt.Color(255, 204, 204));
        btnFront.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnFront.setForeground(new java.awt.Color(102, 153, 255));
        btnFront.setText("Upload front view");
        btnFront.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrontActionPerformed(evt);
            }
        });
        add(btnFront);
        btnFront.setBounds(435, 6, 194, 27);
        add(img);
        img.setBounds(530, 50, 184, 128);

        btnBack.setBackground(new java.awt.Color(255, 204, 204));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(102, 153, 255));
        btnBack.setText("Upload back view");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(435, 212, 194, 27);
        add(img1);
        img1.setBounds(530, 260, 184, 128);

        btnDashBoard.setBackground(new java.awt.Color(255, 204, 204));
        btnDashBoard.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnDashBoard.setForeground(new java.awt.Color(102, 153, 255));
        btnDashBoard.setText("Upload dash board view");
        btnDashBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashBoardActionPerformed(evt);
            }
        });
        add(btnDashBoard);
        btnDashBoard.setBounds(435, 476, 187, 27);
        add(img2);
        img2.setBounds(570, 530, 184, 128);

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 153, 255));
        jLabel24.setText("Contact Phone:");
        add(jLabel24);
        jLabel24.setBounds(110, 640, 110, 19);

        jTextField1.setBackground(new java.awt.Color(255, 204, 204));
        add(jTextField1);
        jTextField1.setBounds(280, 640, 146, 24);

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(30, 690, 89, 27);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/3439d73c70642d1039f6fdc9345403a3.jpeg"))); // NOI18N
        jLabel25.setLabelFor(img);
        jLabel25.setPreferredSize(new java.awt.Dimension(800, 800));
        add(jLabel25);
        jLabel25.setBounds(0, -80, 1310, 920);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        WorkRequest car = new WorkRequest();
        car.setMake(txtMake.getText());
        car.setModel(txtModel.getText());
        car.setYear(txtYear.getText());
        car.setCategory(txtCategory.getText());
        car.setState(txtState.getText());
        car.setCity(txtCity.getText());
        car.setVin(txtVin.getText());
        car.setMileage(txtMileage.getText());
        car.setHorsepower(txtHorsepower.getText());
        car.setInColor(txtInterColor.getText());
        car.setFuelType(txtFuelType.getText());
        car.setTransmission(txtTransmission.getText());
        car.setMpgCity(txtMpgCity.getText());
        car.setMpgHwy(txtMpgHwy.getText());
        car.setDrivetrain(txtDrivetrain.getText());
        car.setContact(jTextField1.getText());
        car.setFrontPicture(path1);
        car.setBackPicture(path2);
        car.setDashBoardPicture(path3);
        car.setSender(userAccount);
        business.getWorkQueue().getWorkRequestList().add(car);
        JOptionPane.showMessageDialog(this, "Used car information saved.");
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnFrontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrontActionPerformed

        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("please choose a zip","zip");
        chooser.setFileFilter(filter);
        chooser.setCurrentDirectory(new File("."));
        int result = chooser.showOpenDialog(null);
        File file=chooser.getSelectedFile();
        if(result==JFileChooser.APPROVE_OPTION){
            String path = ".\\src\\resource";
            File f = new File(path);
            if(!f.exists()){
                f.mkdirs();
            }
            String fileName = chooser.getSelectedFile().getName();
            File file1 = new File(path, fileName);
            if(!file1.exists()){
                try {
                        file1.createNewFile();
                        } catch (IOException e) {
                        e.printStackTrace();
                        }
            }
        }
    }//GEN-LAST:event_btnFrontActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("please choose a pic","img","png");
        chooser.setFileFilter(filter);
        chooser.setCurrentDirectory(new File("."));
        int result = chooser.showOpenDialog(null);
        File file=chooser.getSelectedFile();
        if(result==JFileChooser.APPROVE_OPTION){
            String name = chooser.getSelectedFile().getPath();
            if(name==""||name==null){
                return;
            }
            ImageIcon icon = new ImageIcon(name);
            Image image = icon.getImage();
            Image newImage = image.getScaledInstance(img1.getWidth(), img1.getHeight(), Image.SCALE_DEFAULT);
            System.out.println(img1.getWidth()+""+img1.getHeight());
            icon.setImage(newImage);
            img1.setIcon(icon);
            path2 = name;
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDashBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashBoardActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("please choose a pic","img","png");
        chooser.setFileFilter(filter);
        chooser.setCurrentDirectory(new File("."));
        int result = chooser.showOpenDialog(null);
        File file=chooser.getSelectedFile();
        if(result==JFileChooser.APPROVE_OPTION){
            String name = chooser.getSelectedFile().getPath();
            if(name==""||name==null){
                return;
            }
            ImageIcon icon = new ImageIcon(name);
            Image image = icon.getImage();
            Image newImage = image.getScaledInstance(img2.getWidth(), img2.getHeight(), Image.SCALE_DEFAULT);
            System.out.println(img2.getWidth()+""+img2.getHeight());
            icon.setImage(newImage);
            img2.setIcon(icon);
            path3 = name;
        }
    }//GEN-LAST:event_btnDashBoardActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDashBoard;
    private javax.swing.JButton btnFront;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel img;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDrivetrain;
    private javax.swing.JTextField txtFuelType;
    private javax.swing.JTextField txtHorsepower;
    private javax.swing.JTextField txtInterColor;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtMileage;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtMpgCity;
    private javax.swing.JTextField txtMpgHwy;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtTransmission;
    private javax.swing.JTextField txtVin;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
