/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Person;

/**
 *
 * @author Administrator
 */
public class ViewAcJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAcJPanel
     */
    Person person;
    
    public ViewAcJPanel(Person person) {
        initComponents();
        this.person = person;
        displayPerson();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bntxt = new javax.swing.JTextField();
        brtxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        batxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        atypetxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        balancetxt = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Account");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 823, -1));

        jLabel13.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel13.setText("Bank Name:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        jLabel14.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel14.setText("Bank Routing Number:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        bntxt.setEditable(false);
        bntxt.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        add(bntxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 125, -1));

        brtxt.setEditable(false);
        brtxt.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        add(brtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 125, -1));

        jLabel15.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel15.setText("Bank Account Number:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, -1));

        batxt.setEditable(false);
        batxt.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        batxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batxtActionPerformed(evt);
            }
        });
        add(batxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 125, -1));

        jLabel16.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel16.setText("Account Balance:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, -1, -1));

        atypetxt.setEditable(false);
        atypetxt.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        add(atypetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 610, 125, -1));

        jLabel17.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel17.setText("Account Type:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 610, -1, -1));

        balancetxt.setEditable(false);
        balancetxt.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        add(balancetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 125, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void batxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batxtActionPerformed

    private void displayPerson() {
        bntxt.setText(person.getBankName());
        brtxt.setText(person.getBankRoutingNum());
        batxt.setText(person.getBankAccountNum());
        balancetxt.setText(person.getBalance()); 
        atypetxt.setText(person.getType());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField atypetxt;
    private javax.swing.JTextField balancetxt;
    private javax.swing.JTextField batxt;
    private javax.swing.JTextField bntxt;
    private javax.swing.JTextField brtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    // End of variables declaration//GEN-END:variables
}
