/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Person;

/**
 *
 * @author Administrator
 */
public class ViewMeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewMeJPanel
     */
    Person person;
    
    public ViewMeJPanel(Person person) {
        initComponents();
        this.person = person;
        displayPerson();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        medicaltxt = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        alergy1txt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        alergy2txt = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        alergy3txt = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Medical Record");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 820, -1));

        jLabel23.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel23.setText("Medical Record:");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        medicaltxt.setEditable(false);
        medicaltxt.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        add(medicaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 125, -1));

        jLabel24.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel24.setText("Alergy1:");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        alergy1txt.setEditable(false);
        alergy1txt.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        add(alergy1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 125, -1));

        jLabel25.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel25.setText("Alergy2:");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, -1, -1));

        alergy2txt.setEditable(false);
        alergy2txt.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        add(alergy2txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 125, -1));

        jLabel26.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel26.setText("Alergy3:");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, -1, -1));

        alergy3txt.setEditable(false);
        alergy3txt.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        add(alergy3txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, 125, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void displayPerson() {
        medicaltxt.setText(person.getMedicalNum());
        alergy1txt.setText(person.getAlergy1());
        alergy2txt.setText(person.getAlergy2());
        alergy3txt.setText(person.getAlergy3());       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alergy1txt;
    private javax.swing.JTextField alergy2txt;
    private javax.swing.JTextField alergy3txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JTextField medicaltxt;
    // End of variables declaration//GEN-END:variables
}
