/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Person;

/**
 *
 * @author Administrator
 */
public class ViewAddJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAddJPanel
     */
    Person person;
    
    public ViewAddJPanel(Person person) {
        initComponents();
        this.person = person;
        displayPerson();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        streettxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        citytxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        statetxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        codetxt = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Address");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 820, -1));

        jLabel9.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel9.setText("Street Address:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        streettxt.setEditable(false);
        streettxt.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        streettxt.setAutoscrolls(false);
        add(streettxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 125, -1));

        jLabel10.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel10.setText("City:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));

        citytxt.setEditable(false);
        citytxt.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        add(citytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 125, -1));

        jLabel11.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel11.setText("State:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, -1, -1));

        statetxt.setEditable(false);
        statetxt.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        add(statetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 125, -1));

        jLabel12.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel12.setText("Zip Code:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, -1, -1));

        codetxt.setEditable(false);
        codetxt.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        add(codetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, 125, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void displayPerson() {
        streettxt.setText(person.getStreet());
        citytxt.setText(person.getCity());
        statetxt.setText(person.getState());
        codetxt.setText(person.getCode());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField citytxt;
    private javax.swing.JTextField codetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField statetxt;
    private javax.swing.JTextField streettxt;
    // End of variables declaration//GEN-END:variables
}
