/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.ImageIcon;
import model.Person;


/**
 *
 * @author Administrator
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Person person;
    
    public ViewJPanel(Person person) {
        initComponents();
        this.person = person;
        displayProduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fntxt = new javax.swing.JTextField();
        lntxt = new javax.swing.JTextField();
        phonetxt = new javax.swing.JTextField();
        dbtxt = new javax.swing.JTextField();
        agetxt = new javax.swing.JTextField();
        heighttxt = new javax.swing.JTextField();
        weighttxt = new javax.swing.JTextField();
        socialtxt = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        medicaltxt = new javax.swing.JTextField();
        alergy1txt = new javax.swing.JTextField();
        alergy2txt = new javax.swing.JTextField();
        alergy3txt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        bntxt = new javax.swing.JTextField();
        brtxt = new javax.swing.JTextField();
        batxt = new javax.swing.JTextField();
        atypetxt = new javax.swing.JTextField();
        balancetxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        streettxt = new javax.swing.JTextField();
        citytxt = new javax.swing.JTextField();
        statetxt = new javax.swing.JTextField();
        codetxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lnumtxt = new javax.swing.JTextField();
        ditxt = new javax.swing.JTextField();
        bloodtxt = new javax.swing.JTextField();
        picturelbl = new javax.swing.JLabel();
        detxt = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Demographic"));
        jPanel3.setToolTipText("");
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("First Name:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 36, -1, -1));

        jLabel2.setText("Last Name:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 78, -1, -1));

        jLabel3.setText("Phone Number:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setText("Date of Birth:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 162, -1, -1));

        jLabel5.setText("Age:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 204, -1, -1));

        jLabel6.setText("Height:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 246, -1, -1));

        jLabel7.setText("Weight:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 288, -1, -1));

        jLabel8.setText("Social Security:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        fntxt.setEditable(false);
        jPanel3.add(fntxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 33, 125, -1));

        lntxt.setEditable(false);
        jPanel3.add(lntxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 75, 125, -1));

        phonetxt.setEditable(false);
        jPanel3.add(phonetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 117, 125, -1));

        dbtxt.setEditable(false);
        jPanel3.add(dbtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 159, 125, -1));

        agetxt.setEditable(false);
        jPanel3.add(agetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 201, 125, -1));

        heighttxt.setEditable(false);
        jPanel3.add(heighttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 243, 125, -1));

        weighttxt.setEditable(false);
        weighttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weighttxtActionPerformed(evt);
            }
        });
        jPanel3.add(weighttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 285, 125, -1));

        socialtxt.setEditable(false);
        jPanel3.add(socialtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 327, 125, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 300, 370));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Medical Record"));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setText("Medical Record:");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 36, -1, -1));

        jLabel24.setText("Alergy1:");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 78, -1, -1));

        jLabel25.setText("Alergy2:");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel26.setText("Alergy3:");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 162, -1, -1));

        medicaltxt.setEditable(false);
        jPanel8.add(medicaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 33, 125, -1));

        alergy1txt.setEditable(false);
        jPanel8.add(alergy1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 75, 125, -1));

        alergy2txt.setEditable(false);
        jPanel8.add(alergy2txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 117, 125, -1));

        alergy3txt.setEditable(false);
        jPanel8.add(alergy3txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 159, 125, -1));

        add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 390, 300, 200));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Account"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Bank Name:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 36, -1, -1));

        jLabel14.setText("Bank Routing Number:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 78, -1, -1));

        jLabel15.setText("Bank Account Number:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel16.setText("Account Balance:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 162, -1, -1));

        jLabel17.setText("Account Type:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 205, -1, -1));

        bntxt.setEditable(false);
        jPanel2.add(bntxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 33, 125, -1));

        brtxt.setEditable(false);
        jPanel2.add(brtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 75, 125, -1));

        batxt.setEditable(false);
        batxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batxtActionPerformed(evt);
            }
        });
        jPanel2.add(batxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 117, 125, -1));

        atypetxt.setEditable(false);
        jPanel2.add(atypetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 200, 125, -1));

        balancetxt.setEditable(false);
        balancetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balancetxtActionPerformed(evt);
            }
        });
        jPanel2.add(balancetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 159, 125, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 13, 470, 240));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Address"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Street Address:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 56, -1, -1));

        jLabel10.setText("City:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 98, -1, -1));

        jLabel11.setText("State:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel12.setText("Zip Code:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 182, -1, -1));

        streettxt.setEditable(false);
        streettxt.setAutoscrolls(false);
        jPanel1.add(streettxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 53, 125, -1));

        citytxt.setEditable(false);
        jPanel1.add(citytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 95, 125, -1));

        statetxt.setEditable(false);
        jPanel1.add(statetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 137, 125, -1));

        codetxt.setEditable(false);
        jPanel1.add(codetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 179, 125, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 595, 300, 240));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Driver's license"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setText("License Number:");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 64, -1, -1));

        jLabel19.setText("Date It Was Issued:");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 106, -1, -1));

        jLabel20.setText("Date of Expiration:");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 148, -1, -1));

        jLabel21.setText("Blood Type:");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel22.setText("Picture:");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        lnumtxt.setEditable(false);
        lnumtxt.setAutoscrolls(false);
        jPanel4.add(lnumtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 61, 125, -1));

        ditxt.setEditable(false);
        ditxt.setAutoscrolls(false);
        jPanel4.add(ditxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 103, 125, -1));

        bloodtxt.setEditable(false);
        bloodtxt.setAutoscrolls(false);
        jPanel4.add(bloodtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 187, 125, -1));
        jPanel4.add(picturelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 330, 220));

        detxt.setEditable(false);
        detxt.setAutoscrolls(false);
        jPanel4.add(detxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 145, 125, -1));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 470, 575));
    }// </editor-fold>//GEN-END:initComponents

    private void weighttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weighttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weighttxtActionPerformed

    private void batxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batxtActionPerformed

    private void balancetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balancetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balancetxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agetxt;
    private javax.swing.JTextField alergy1txt;
    private javax.swing.JTextField alergy2txt;
    private javax.swing.JTextField alergy3txt;
    private javax.swing.JTextField atypetxt;
    private javax.swing.JTextField balancetxt;
    private javax.swing.JTextField batxt;
    private javax.swing.JTextField bloodtxt;
    private javax.swing.JTextField bntxt;
    private javax.swing.JTextField brtxt;
    private javax.swing.JTextField citytxt;
    private javax.swing.JTextField codetxt;
    private javax.swing.JTextField dbtxt;
    private javax.swing.JTextField detxt;
    private javax.swing.JTextField ditxt;
    private javax.swing.JTextField fntxt;
    private javax.swing.JTextField heighttxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField lntxt;
    private javax.swing.JTextField lnumtxt;
    private javax.swing.JTextField medicaltxt;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JLabel picturelbl;
    private javax.swing.JTextField socialtxt;
    private javax.swing.JTextField statetxt;
    private javax.swing.JTextField streettxt;
    private javax.swing.JTextField weighttxt;
    // End of variables declaration//GEN-END:variables

    private void displayProduct() {
        fntxt.setText(person.getFirstName());
        lntxt.setText(person.getLastName());
        phonetxt.setText(person.getPhone());
        dbtxt.setText(person.getDate());
        agetxt.setText(person.getAge());
        heighttxt.setText(person.getHeight());
        weighttxt.setText(person.getWeight());
        socialtxt.setText(person.getSocialNum());
        streettxt.setText(person.getStreet());
        citytxt.setText(person.getCity());
        statetxt.setText(person.getState());
        codetxt.setText(person.getCode());
        bntxt.setText(person.getBankName());
        brtxt.setText(person.getBankRoutingNum());
        batxt.setText(person.getBankAccountNum());
        balancetxt.setText(person.getBalance()); 
        atypetxt.setText(person.getType());
        lnumtxt.setText(person.getLicenseNum());
        ditxt.setText(person.getIssuedDate());
        detxt.setText(person.getExpirDate());
        bloodtxt.setText(person.getExpirDate());
        bloodtxt.setText(person.getBlood());
        ImageIcon img = new ImageIcon("src\\resource\\" + person.getPicture());
        picturelbl.setIcon(img);
        medicaltxt.setText(person.getMedicalNum());
        alergy1txt.setText(person.getAlergy1());
        alergy2txt.setText(person.getAlergy2());
        alergy3txt.setText(person.getAlergy3());       
    }
}
