/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Buyer;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.WorkQueue.AbstractQuestion;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.CardLayout;
import java.awt.Component;
import ui.SystemAdminRole.SystemAdminWorkAreaJPanel;

/**
 *
 * @author Ke
 */
public class BookAppointment extends javax.swing.JPanel {
    public JPanel container;
    public EcoSystem business;
    private AbstractQuestion course;

    /**
     * Creates new form BookAppointmentJPanel
     */
    public BookAppointment(JPanel userProcessContainer, EcoSystem business, AbstractQuestion course) {
        initComponents();
        this.container = userProcessContainer;
        this.business = business;
        this.course = course;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setText("Date:");
        add(jLabel1);
        jLabel1.setBounds(370, 220, 40, 18);

        jLabel2.setText("Phone Number:");
        add(jLabel2);
        jLabel2.setBounds(350, 310, 130, 18);

        jLabel3.setText("Name:");
        add(jLabel3);
        jLabel3.setBounds(380, 390, 50, 18);
        add(jTextField1);
        jTextField1.setBounds(490, 220, 115, 24);
        add(jTextField2);
        jTextField2.setBounds(490, 310, 115, 24);
        add(jTextField3);
        jTextField3.setBounds(490, 390, 115, 24);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 153, 255));
        jButton1.setText("Reserve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(450, 460, 83, 27);

        jLabel10.setFont(new java.awt.Font("Skia", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(99, 148, 249));
        jLabel10.setText("Book appointment");
        add(jLabel10);
        jLabel10.setBounds(40, 10, 212, 120);

        jLabel8.setText("—————————————————————————————————————————————————");
        add(jLabel8);
        jLabel8.setBounds(90, 60, 735, 100);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        course.setDate(jTextField1.getText());
        course.setPhone(jTextField2.getText());
        course.setName(jTextField3.getText());
        DB4OUtil.getInstance().storeSystem(business);
        JOptionPane.showMessageDialog(this, "Saved.");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
