/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Buyer;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Router;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AbstractQuestion;
import Business.WorkQueue.WorkRequest;
import java.awt.GridLayout;
import javax.swing.JPanel;
import ui.components.QuestionCell;


/**
 *
 * @author Ke
 */
public class BuyerQuestion extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;

    public BuyerQuestion(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        initFiles(/*course.getFileDirectory()*/);
    }

    private void initFiles(/*FileDirectory fileDir*/){

        /*contentPanel.setLayout(new GridLayout(0,2));

        int cell_H = contentPanel.getWidth() * 4 / 3;

        for (File file : fileDir){
            FileCell cell = new FileCell(file);
            contentPanel.add(cell);
            cell.setPreferredSize(new Dimension(contentPanel.getWidth(),contentPanel.getWidth() * 4 / 3));
        }

        scrollPanel.setSize(contentPanel.getWidth(), cell_H * fileDir.getList().size() / 2 + 1);

        contentPanel.setSize(contentPanel.getWidth(), cell_H * fileDir.getList().size() / 2 + 1);

        contentPanel.setPreferredSize(new Dimension(contentPanel.getWidth(), cell_H * fileDir.getList().size() / 2 + 1));
        updateUI();*/
        contentPanel.setLayout(new GridLayout(0,1));

        for (AbstractQuestion request : business.getWorkQueue().getWorkRequestList()){
            if(request.getSender()!=null){
                QuestionCell cell = new QuestionCell(userProcessContainer,userAccount,organization,enterprise,business,request);
                contentPanel.add(cell);
            }
        }
        
        updateUI();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanel = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        questionjTextField = new javax.swing.JTextField();
        requestTestJButton = new javax.swing.JButton();
        backJButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1024, 768));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 994, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1996, Short.MAX_VALUE)
        );

        scrollPanel.setViewportView(contentPanel);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setText("Question:");

        questionjTextField.setBackground(new java.awt.Color(255, 204, 204));

        requestTestJButton.setBackground(new java.awt.Color(255, 204, 204));
        requestTestJButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        requestTestJButton.setForeground(new java.awt.Color(102, 153, 255));
        requestTestJButton.setText("Ask");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });

        backJButton2.setBackground(new java.awt.Color(255, 204, 204));
        backJButton2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        backJButton2.setForeground(new java.awt.Color(102, 153, 255));
        backJButton2.setText("<< Back");
        backJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanel)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(questionjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156)
                .addComponent(requestTestJButton)
                .addGap(140, 140, 140)
                .addComponent(backJButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(questionjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(requestTestJButton)
                        .addComponent(backJButton2)))
                .addContainerGap(784, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        String q = questionjTextField.getText();

        WorkRequest question = new WorkRequest();
        question.setQuestion(q);
        question.setSender(userAccount);

        userAccount.getWorkQueue().getWorkRequestList().add(question);
        business.getWorkQueue().getWorkRequestList().add(question);
        DB4OUtil.getInstance().storeSystem(business);
        updateUI();
        //enterprise.getWorkQueue().getWorkRequestList().add(question);

        /*Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof BuyerOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getQuestionDirectory().getQuestionList().add(question);
            userAccount.getQuestionDirectory().getQuestionList().add(question);
        }
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof CustomerServiceOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(question);
            JOptionPane.showMessageDialog(null, "Please input username or password!");
            //userAccount.getWorkQueue().getWorkRequestList().add(request);
        }*/

    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton2ActionPerformed
        Router.getInstance(null).back(0);
    }//GEN-LAST:event_backJButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton backJButton2;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField questionjTextField;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JScrollPane scrollPanel;
    // End of variables declaration//GEN-END:variables
}
