/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Buyer;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AbstractQuestion;
import java.awt.GridLayout;
import java.io.File;
import javax.swing.JPanel;
import ui.components.ListingsCell;
import ui.components.PictureCell;
import ui.components.TagCell;

/**
 *
 * @author Ke
 */
public class ViewHousingInfo extends javax.swing.JPanel {

    /**
     * Creates new form FileJPanel
     */
    public JPanel container;
    public EcoSystem system;
    private UserAccount userAccount;
    AbstractQuestion course;
    String[] path = new String[10];
    int i = 0;
    
    public ViewHousingInfo(JPanel userProcessContainer, EcoSystem system, UserAccount userAccount, AbstractQuestion course) {
        initComponents();
        this.container = userProcessContainer;
        this.system = system;
        this.userAccount = userAccount;
        this.course = course;
        path = course.getPath();
        View();
    }
    
    public void View(){
        txtState.setText(course.getState()); 
        txtCity.setText(course.getCity());    
        txtAd1.setText(course.getAddress1());
        txtArea.setText(String.valueOf(course.getArea()));  
        txtArea2.setText(String.valueOf(course.getArea2())); 
        txtBed.setText(String.valueOf(course.getBedroom()));
        txtBath.setText(String.valueOf(course.getBathroom()));
        txtArea2.setText(String.valueOf(course.getFloor()));
        txtRent.setText(String.valueOf(course.getRent()));
        
        contentPanel.setLayout(new GridLayout(1,0));        
        if(path == null)
            return;
        for(int i = 0; i<10 ;i++){
            if(path[i] != null){
                PictureCell cell = new PictureCell(container,userAccount,system, path[i]);
                contentPanel.add(cell);
            }
        }
        
        /*ImageIcon icon = new ImageIcon(car.getFrontPicture());
        img.setIcon(icon);  
        ImageIcon icon1 = new ImageIcon(car.getBackPicture());
        img1.setIcon(icon1); 
        ImageIcon icon2 = new ImageIcon(car.getDashBoardPicture());
        img2.setIcon(icon2); */
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtAd1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtRent = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBed = new javax.swing.JTextField();
        txtBath = new javax.swing.JTextField();
        txtArea2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 153, 255));
        jLabel10.setText("Listing Info");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 45, -1, -1));

        jLabel8.setText("—————————————————————————————————————————————————");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 86, -1, -1));

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 153, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("State:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 49, -1));

        txtState.setEditable(false);
        txtState.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        txtState.setForeground(new java.awt.Color(51, 153, 255));
        add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 100, -1));

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 153, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Address:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        txtAd1.setEditable(false);
        txtAd1.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        txtAd1.setForeground(new java.awt.Color(51, 153, 255));
        add(txtAd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 402, -1));

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 153, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Expected rent:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 120, -1));

        txtRent.setEditable(false);
        txtRent.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        txtRent.setForeground(new java.awt.Color(51, 153, 255));
        add(txtRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 132, -1));

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 153, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Area:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 89, -1));

        txtCity.setEditable(false);
        txtCity.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        txtCity.setForeground(new java.awt.Color(51, 153, 255));
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 100, -1));

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 153, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("City:");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 49, -1));

        txtArea.setEditable(false);
        txtArea.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        txtArea.setForeground(new java.awt.Color(51, 153, 255));
        add(txtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 100, -1));

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 153, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("sqft");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 255));
        jLabel6.setText("Unit type:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 91, -1));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 153, 255));
        jLabel11.setText("bedroom");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 153, 255));
        jLabel9.setText("bathroom");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, -1, -1));

        txtBed.setEditable(false);
        txtBed.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        txtBed.setForeground(new java.awt.Color(51, 153, 255));
        add(txtBed, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 32, -1));

        txtBath.setEditable(false);
        txtBath.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        txtBath.setForeground(new java.awt.Color(51, 153, 255));
        add(txtBath, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 32, -1));

        txtArea2.setEditable(false);
        txtArea2.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        txtArea2.setForeground(new java.awt.Color(51, 153, 255));
        add(txtArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 100, -1));

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 153, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("sqft lot");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 60, -1));

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 153, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("$ ");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 30, -1));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 917, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(contentPanel);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 870, 300));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAd1;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtArea2;
    private javax.swing.JTextField txtBath;
    private javax.swing.JTextField txtBed;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtRent;
    private javax.swing.JTextField txtState;
    // End of variables declaration//GEN-END:variables

}
